-- Clear existing data
TRUNCATE words, meanings, categories, users RESTART IDENTITY CASCADE;

-- Categories
INSERT INTO categories (name, description) VALUES 
('nouns', 'People, places, things, or ideas.'),
('verbs', 'Action words or states of being.'),
('adjectives', 'Words that describe or modify nouns.'),
('adverbs', 'Words that modify verbs, adjectives, or other adverbs.'),
('phrases', 'Common Spanish expressions and idioms.');

-- Words
INSERT INTO words (word) VALUES
-- nouns
('la casa'),
('el perro'),
('la ciudad'),
('el agua'),
('la familia'),
('el trabajo'),
('la mesa'),
('el libro'),
('la mano'),
('el tiempo'),
('la noche'),
('el día'),
('la vida'),
('el hombre'),
('la mujer'),
('el niño'),
('la puerta'),
('el coche'),
('la comida'),
('el dinero'),
-- verbs
('hablar'),
('comer'),
('vivir'),
('tener'),
('ser'),
('estar'),
('hacer'),
('poder'),
('querer'),
('ir'),
('venir'),
('saber'),
('conocer'),
('dar'),
('ver'),
('dormir'),
('escribir'),
('leer'),
('escuchar'),
('caminar'),
-- adjectives
('bueno'),
('malo'),
('grande'),
('pequeño'),
('feliz'),
('triste'),
('rápido'),
('lento'),
('bonito'),
('feo'),
('nuevo'),
('viejo'),
('caliente'),
('frío'),
('fácil'),
('difícil'),
('rico'),
('pobre'),
('alto'),
('bajo'),
-- adverbs
('siempre'),
('nunca'),
('también'),
('muy'),
('bien'),
('mal'),
('aquí'),
('allí'),
('hoy'),
('mañana'),
-- phrases
('buenos días'),
('buenas noches'),
('por favor'),
('gracias'),
('de nada'),
('lo siento'),
('¿cómo estás?'),
('me llamo'),
('¿cuánto cuesta?'),
('no entiendo');

-- Meanings
INSERT INTO meanings (word_id, category_id, definition, example_sentence) VALUES
-- nouns (category_id = 1)
(1, 1, 'House; a building for human habitation.', 'Mi casa es muy grande. (My house is very big.)'),
(2, 1, 'Dog; a domesticated carnivorous mammal.', 'El perro corre en el parque. (The dog runs in the park.)'),
(3, 1, 'City; a large town.', 'La ciudad de Madrid es muy bonita. (The city of Madrid is very beautiful.)'),
(4, 1, 'Water; a clear liquid essential for life.', 'Necesito agua, por favor. (I need water, please.)'),
(5, 1, 'Family; a group of related people.', 'Mi familia es muy importante para mí. (My family is very important to me.)'),
(6, 1, 'Work; a job or occupation.', 'El trabajo empieza a las nueve. (Work starts at nine.)'),
(7, 1, 'Table; a piece of furniture with a flat top.', 'La mesa está en la cocina. (The table is in the kitchen.)'),
(8, 1, 'Book; a written or printed work.', 'Este libro es muy interesante. (This book is very interesting.)'),
(9, 1, 'Hand; the end part of a person''s arm.', 'Dame la mano. (Give me your hand.)'),
(10, 1, 'Time or weather; depending on context.', 'No tengo tiempo. (I don''t have time.)'),
(11, 1, 'Night; the time from sunset to sunrise.', 'La noche es muy tranquila. (The night is very quiet.)'),
(12, 1, 'Day; a 24-hour period.', 'Hoy es un buen día. (Today is a good day.)'),
(13, 1, 'Life; the existence of a living being.', 'La vida es bella. (Life is beautiful.)'),
(14, 1, 'Man; an adult male human.', 'El hombre trabaja mucho. (The man works a lot.)'),
(15, 1, 'Woman; an adult female human.', 'La mujer lee un libro. (The woman reads a book.)'),
(16, 1, 'Child; a young human being.', 'El niño juega en el parque. (The child plays in the park.)'),
(17, 1, 'Door; a hinged barrier used to close an opening.', 'Cierra la puerta, por favor. (Close the door, please.)'),
(18, 1, 'Car; a road vehicle powered by an engine.', 'Mi coche es rojo. (My car is red.)'),
(19, 1, 'Food; any nutritious substance eaten by humans.', 'La comida está deliciosa. (The food is delicious.)'),
(20, 1, 'Money; a medium of exchange.', 'No tengo dinero. (I don''t have money.)'),
-- verbs (category_id = 2)
(21, 2, 'To speak or talk.', 'Yo hablo español. (I speak Spanish.)'),
(22, 2, 'To eat.', 'Vamos a comer. (We are going to eat.)'),
(23, 2, 'To live.', 'Quiero vivir en España. (I want to live in Spain.)'),
(24, 2, 'To have.', 'Tengo dos hermanos. (I have two brothers.)'),
(25, 2, 'To be (permanent characteristics).', 'Ella es médica. (She is a doctor.)'),
(26, 2, 'To be (temporary states or conditions).', 'Estoy cansado. (I am tired.)'),
(27, 2, 'To do or make.', '¿Qué haces? (What are you doing?)'),
(28, 2, 'To be able to; can.', 'No puedo venir hoy. (I can''t come today.)'),
(29, 2, 'To want or love.', 'Quiero un café. (I want a coffee.)'),
(30, 2, 'To go.', 'Voy al mercado. (I am going to the market.)'),
(31, 2, 'To come.', '¿Puedes venir mañana? (Can you come tomorrow?)'),
(32, 2, 'To know (facts or information).', 'No sé la respuesta. (I don''t know the answer.)'),
(33, 2, 'To know (people or places).', 'Conozco Madrid bien. (I know Madrid well.)'),
(34, 2, 'To give.', 'Te doy mi número. (I''ll give you my number.)'),
(35, 2, 'To see.', 'Veo las estrellas. (I see the stars.)'),
(36, 2, 'To sleep.', 'Duermo ocho horas. (I sleep eight hours.)'),
(37, 2, 'To write.', 'Escribo una carta. (I am writing a letter.)'),
(38, 2, 'To read.', 'Leo el periódico. (I read the newspaper.)'),
(39, 2, 'To listen.', 'Escucha la música. (Listen to the music.)'),
(40, 2, 'To walk.', 'Camino al trabajo. (I walk to work.)'),
-- adjectives (category_id = 3)
(41, 3, 'Good; of high quality or an acceptable standard.', 'Es un buen estudiante. (He is a good student.)'),
(42, 3, 'Bad; of poor quality or low standard.', 'El tiempo está malo hoy. (The weather is bad today.)'),
(43, 3, 'Big or large.', 'Vivo en una ciudad grande. (I live in a big city.)'),
(44, 3, 'Small or little.', 'Tengo un apartamento pequeño. (I have a small apartment.)'),
(45, 3, 'Happy; feeling or showing pleasure.', 'Estoy muy feliz hoy. (I am very happy today.)'),
(46, 3, 'Sad; feeling sorrow or unhappiness.', 'El niño está triste. (The child is sad.)'),
(47, 3, 'Fast or quick.', 'El coche es muy rápido. (The car is very fast.)'),
(48, 3, 'Slow.', 'El tráfico está muy lento. (The traffic is very slow.)'),
(49, 3, 'Pretty or beautiful.', 'Qué vestido tan bonito. (What a pretty dress.)'),
(50, 3, 'Ugly.', 'El edificio es muy feo. (The building is very ugly.)'),
(51, 3, 'New.', 'Tengo un teléfono nuevo. (I have a new phone.)'),
(52, 3, 'Old.', 'Esta es una ciudad muy vieja. (This is a very old city.)'),
(53, 3, 'Hot or warm.', 'El café está caliente. (The coffee is hot.)'),
(54, 3, 'Cold.', 'El agua está fría. (The water is cold.)'),
(55, 3, 'Easy.', 'El examen fue fácil. (The exam was easy.)'),
(56, 3, 'Difficult or hard.', 'El español no es difícil. (Spanish is not difficult.)'),
(57, 3, 'Rich or delicious (food context).', 'Esta paella está muy rica. (This paella is very delicious.)'),
(58, 3, 'Poor.', 'El país es muy pobre. (The country is very poor.)'),
(59, 3, 'Tall or high.', 'Mi hermano es muy alto. (My brother is very tall.)'),
(60, 3, 'Short or low.', 'La silla es muy baja. (The chair is very low.)'),
-- adverbs (category_id = 4)
(61, 4, 'Always.', 'Siempre llego a tiempo. (I always arrive on time.)'),
(62, 4, 'Never.', 'Nunca como carne. (I never eat meat.)'),
(63, 4, 'Also or too.', 'Yo también quiero ir. (I also want to go.)'),
(64, 4, 'Very.', 'Estoy muy cansado. (I am very tired.)'),
(65, 4, 'Well or good.', 'Hablas español muy bien. (You speak Spanish very well.)'),
(66, 4, 'Badly or poorly.', 'Me siento mal hoy. (I feel bad today.)'),
(67, 4, 'Here.', 'Ven aquí, por favor. (Come here, please.)'),
(68, 4, 'There.', 'El banco está allí. (The bank is there.)'),
(69, 4, 'Today.', 'Hoy hace mucho calor. (It is very hot today.)'),
(70, 4, 'Tomorrow.', 'Mañana tengo una reunión. (Tomorrow I have a meeting.)'),
-- phrases (category_id = 5)
(71, 5, 'Good morning; a greeting used in the morning.', 'Buenos días, ¿cómo estás? (Good morning, how are you?)'),
(72, 5, 'Good night; a farewell used at night.', 'Buenas noches, hasta mañana. (Good night, see you tomorrow.)'),
(73, 5, 'Please; used to make a polite request.', '¿Me das agua, por favor? (Can you give me water, please?)'),
(74, 5, 'Thank you; an expression of gratitude.', 'Gracias por tu ayuda. (Thank you for your help.)'),
(75, 5, 'You''re welcome; a response to thank you.', 'De nada, es un placer. (You''re welcome, it''s a pleasure.)'),
(76, 5, 'I''m sorry; an expression of apology.', 'Lo siento, fue mi culpa. (I''m sorry, it was my fault.)'),
(77, 5, 'How are you; a common greeting.', '¿Cómo estás? Bien, gracias. (How are you? Fine, thanks.)'),
(78, 5, 'My name is; used to introduce yourself.', 'Me llamo Carlos. (My name is Carlos.)'),
(79, 5, 'How much does it cost; used when shopping.', '¿Cuánto cuesta este libro? (How much does this book cost?)'),
(80, 5, 'I don''t understand; used when you need clarification.', 'No entiendo, ¿puedes repetir? (I don''t understand, can you repeat?)');